encoding: utf-8
name: Dream Sketch Code
author: Douglas Cuthbertson
description: An exploration of software development
avatar: http://www.gravatar.com/avatar/71b1b3ffdc9fec49fe58bb0dfa43a402

# Github Configuration
highligher: pygments   # The default highlighter for GitHub Pages
#highlighter: rouge   # Maybe one day GitHub Pages will support rouge

# GitHub Pages Metadata (see https://help.github.com/articles/repository-metadata-on-github-pages/)
github:
  {
    "pages_hostname": "github.io",
    "owner_gravatar_url": "http://www.gravatar.com/avatar/71b1b3ffdc9fec49fe58bb0dfa43a402",
    "url": "http://dbc60.github.io/", // (or the CNAME)
  }

# My Configuration
include:      [
              ]

# Exclude these files from your production _site
exclude:      [
                'config.rb',
                'Gemfile',
                'Gemfile.lock',
              ]

gems:         [
                'jekyll-sitemap',
                'jekyll-paginate'
              ]

# TODO(doug): What do these settings affect?
# timezone:    nil
# future:      true
# show_drafts: false
# limit_posts: 0

#permalink: /:title/
#permalink: date
permalink: /blog/:year/:title/

#paginate_path: '/blog/page:num'
#permalink: /:year/:title/
#permalink: /:slug/
# Pagination can automatically generate the appropriate files and folders you need for paginated listings.
# It only works within HTML file (like your /index.html file). Jekyll 2 has pagination built-in. You'll need
# to include the jekyll-paginate plugin-in in your Gemfile and in _config.yml under "gems" for Jekyll 3. make
# sure GitHub supports jekyll-paginate (after they upgrade to Jekyll 3)
#
# Unfortunately setting permalink causes pagination to break. It may be better to just limit the
# front page to 5 or 10 posts, and include an archive link in the navigation section.
#paginate_path: '/blog/:year/:title/page:num/'
#paginate:      5
#paginate: 10          # Posts per page on the blog index
#paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
#recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_separator: "<!--more-->"
#markdown:       kramdown
kramdown:
  input: GFM   # GFM - Github Flavored Markdown.
  use_coderay: true
  coderay:
    coderay_line_numbers: true
    coderay_css: class

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript",
                 "tables", "with_toc_data"]
markdown_ext:   markdown,mkdown,mkdn,mkd,md

#  syntax_highlighter: pygments # Change to rouge after updating to Jekyll 3.0
#  syntax_highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded
  sass_dir: _sass

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: doug.cuthbertson@gmail.com
  facebook:
  flickr:
  github: dbc60
  instagram:
  linkedin: douglas-cuthbertson-0487001
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: DougCuthbertson
  stackoverflow: users/165347/doug-cuthbertson
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DougCuthbertson
  author: Douglas Cuthbertson

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: cuthbertson

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your User repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
